on: 
    workflow_dispatch:

jobs:
  changed:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            package-json:
              - 'projects/${{GITHUB_WORKFLOW}}/package.json'

  publish:
    if: ${{ changed.steps.filter.package-json == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
