name: queue-monitor-panel
on: 
    push:
        branches: main
    workflow_dispatch:

jobs:
  build:
    env:
        OUTPUT_PATH: "./dist/$GITHUB_WORKFLOW"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci

      - run: npm run build -- $GITHUB_WORKFLOW

      - run: find ${{env.OUTPUT_PATH}}
      - run: npm publish --access public --dry-run
        working-directory: ./dist/queue-monitor-panel
    
